server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Disable caching for the HTML entry point
    location = /index.html {
        add_header Cache-Control "no-store";
    }
}
